; --------------------------------------------------------------------------;
;;;;;;;;;;;;;;;;;;;; READ BELOW BEFORE EDITING THIS FILE ;;;;;;;;;;;;;;;;;;;;
; --------------------------------------------------------------------------;

;;; This default configuration file is placed in volgrids' repository root for convenience.
;;; As consequence, it is not packed when installing volgrids as a package (e.g., via pip).
;;;
;;; Therefore, this file will only be used when NOT running volgrids as a package
;;; (regardless of whether volgrids is installed or not). For example:
;;;
;;; python3 volgrids smiffer -h                  --> uses this file
;;; python3 another/location/volgrids smiffer -h --> uses this file
;;; python3 -m volgrids smiffer -h               --> DOES NOT use this file
;;; volgrids smiffer -h                          --> DOES NOT use this file
;;;
;;; When this config file is not used, all parameters use default hardcoded values. They are the same as the ones in this file.
;;; In any case, this file can always be used by specifying its path with the -c/--config option.
;;; e.g.: volgrids smiffer struct.pdb -c config_volgrids.ini


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; VOLGRIDS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;; OUTPUT
OUT_FORMAT = MRC
    ;;; Format in which to pack the grid output. options:
    ;;; "DX": Human-readable format (heavy). Tested with VMD, Chimera, ChimeraX, UnityMol.
    ;;; "BIN": Binary format (light).
    ;;; "MRC": Binary format (light). Tested with VMD, Chimera, ChimeraX.
    ;;; "CCP4": Similar to MRC.
    ;;; "CMAP": Compressed binary format (very light). Tested with ChimeraX.
OUT_CMAP_COMPRESSION = 9    ; gzip compression level for CMAP files (0-9); h5py default is 4
OUT_WARNING_NPOINTS = 1.0e99; if the grid would exceed this amount of points, trigger a warning with possibility to abort
OUT_OVERWRITE_OK = true     ; whether to allow overwriting existing files without asking for confirmation


;;;;;;;;;;;;;;;;;;;;;;;; BOX
BOX_PADDING = 5 ; extra padding at the box outlines, only applies to whole mode
BOX_TIGHT_TRAJ = false ; (trajectories) recompute a tight box around the structure at every frame.
    ;;; Otherwise use a common box that can cover the structure in all the frames.
    ;;; Setting it to true has the advantage of (potentially significant) smaller output size.
    ;;; But it has the caveat that CMAP files with heterogeneous boxes cannot be currently opened as a map series by ChimeraX (despite the files being valid HDF5 files).
BOX_FORCE_EQUILATERAL = false ; forces the grid to have the same resolution in all dimensions
BOX_FROM_DELTAS = true ; whether to use fixed dx,dy,dz and let xres,yres,zres change (or the opposite)

BOX_DX = 0.25 ; voxel size in x dimension (in Angstroms), used when BOX_FROM_DELTAS=true (resolutions change)
BOX_DY = 0.25 ; voxel size in y dimension (in Angstroms), used when BOX_FROM_DELTAS=true (resolutions change)
BOX_DZ = 0.25 ; voxel size in z dimension (in Angstroms), used when BOX_FROM_DELTAS=true (resolutions change)

BOX_XRES = 200 ; number of voxels in x dimension, used when BOX_FROM_DELTAS=false (deltas change)
BOX_YRES = 200 ; number of voxels in y dimension, used when BOX_FROM_DELTAS=false (deltas change)
BOX_ZRES = 200 ; number of voxels in z dimension, used when BOX_FROM_DELTAS=false (deltas change)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; SMIFFER ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;; SMIFS CALCULATION
SMIF_STK   = true ; whether to calculate SMIFs for stacking interactions
SMIF_HBA   = true ; whether to calculate SMIFs for hydrogen bond acceptors
SMIF_HBD   = true ; whether to calculate SMIFs for hydrogen bond donors
SMIF_APBS  = true ; whether to calculate electrostatic interactions grid via APBS
SMIF_HPHOB = true ; whether to calculate SMIFs for hydrophobic interactions
SMIF_HPHIL = true ; whether to calculate SMIFs for hydrophilic interactions

SMIF_USE_HYDROGENS = true  ; whether to use the hydrogens from the structure (if available) for calculating hbdonors
SMIF_HB_ONLY_NBASE = false ; whether to only consider the RNA/DNA nucleobases for calculating hbonds (ignores the backbone)


;;;;;;;;;;;;;;;;;;;;;;;; TRIMMING
;;;;; TOGGLES
TRIM_OCCUPANCY = true  ; set voxels to zero if they are too close to any atom in the structure (i.e. they are "occupied" by the structure)
TRIM_SPHERE    = true  ; set voxels to zero if they are outside an user-defined sphere. Only applies for pocket-sphere mode
TRIM_RNDS      = false ; set voxels to zero if they are disconnected from the central cluster of SMIF values in a user-defined sphere.
    ;;; Only applies for pocket-sphere mode. Can be problematic (e.g. slow, aggressive trimming); use with caution.
TRIM_FARAWAY   = true  ; set voxels to zero if they are too far away from any atom in the structure. Only applies for pocket-sphere mode
TRIM_CAVITIES  = false ; run "cavities finder" and trim outside the cavities
TRIM_SAVE = false ; saves the logical inverse of the trimming mask using TRIM_OCC_DIST_MID

;;;;; OCCUPANCY TRIMMING
TRIM_OCC_DIST_SHORT = 2.5 ; occupancy radius of atoms when considering: hydrophilic
TRIM_OCC_DIST_MID   = 3.0 ; occupancy radius of atoms when considering: hydrophobic, hbonds, stacking
TRIM_OCC_DIST_LONG  = 3.5 ; occupancy radius of atoms when considering: apbs

;;;;; RANDOM SEARCH TRIMMING
TRIM_RNDS_MAX_DIST = inf
TRIM_RNDS_CUBE_RADIUS = 4

;;;;; FARAWAY TRIMMING
TRIM_FARAWAY_DIST = 7.0 ; trim any point that is further than this distance from any atom in the structure


;;;;;;;;;;;;;;;;;;;;;;;; CAVITIES
;;;;; NOTE: cavities options (TRIM_CAVITIES, CAV_SAVE) currently require TRIM_OCCUPANCY to be true, otherwise they will be ignored
;;;;; even though cavities is tightly associated to trimming operations, they can also be used to weight SMIFs instead of trimming them
;;;;; hence configs from this section don't start with TRIM_, but with a distinctive CAV_ instead
CAV_THRESHOLD = 3.0 ; sensible values: 1,2,3. 0 (and below) deletes no points, 4 (and above) deletes all points
CAV_NPASSES = 2 ; refine the cavities search by performing evenly spaced rotations between 0 and 90 degrees.
    ;;; CAV_NPASSES = 1: one pass with the original grid orientation
    ;;; CAV_NPASSES = 2: 0 deg rotation + 45 deg rotation , then average
    ;;; CAV_NPASSES = 3: 0 deg + 30 deg + 60 deg rotations, then average
    ;;; and so on. Consider that a single rotation depends at most on 6 calls to scipy.ndimage.rotate
    ;;; it's recommended to set "BOX_FORCE_EQUILATERAL=true" for better behaviour, specially near the grid boundaries (although it will increase computation time)
CAV_WEIGHT = 0.0 ; values different than 0 will weight the SMIFs with the cavities values.
CAV_SAVE = false ; run "cavities finder" and save its grid


;;;;;;;;;;;;;;;;;;;;;;;; SMIF MODEL PARAMETERS
PARAM_STK_SCALE = 3.5 ; scale factor for the energy of the stacking interactions
PARAM_HB_SCALE  = 3.5 ; scale factor for the energy of the hbonds interactions

PARAM_HPHOB_DIST_MU = 4.4
PARAM_HBHOB_DIST_SIGMA = 0.3

PARAM_HPHIL_DIST_MU = 3.0
PARAM_HPHIL_DIST_SIGMA = 0.15

PARAM_HBA_ANGLE_MU = 129.9
PARAM_HBA_DIST_MU = 2.93
PARAM_HBA_ANGLE_SIGMA = 20.0 ; 29.3 originally (given precisely)
PARAM_HBA_DIST_SIGMA = 0.21

PARAM_HBD_FREE_ANGLE_MU = 109.0
PARAM_HBD_FREE_DIST_MU = 2.93
PARAM_HBD_FREE_ANGLE_SIGMA = 20.0 ; 20.0 originally (inferred from .figure)
PARAM_HBD_FREE_DIST_SIGMA = 0.21

PARAM_HBD_FIXED_ANGLE_MU = 180.0
PARAM_HBD_FIXED_DIST_MU = 2.93
PARAM_HBD_FIXED_ANGLE_SIGMA = 30.0
PARAM_HBD_FIXED_DIST_SIGMA = 0.21

PARAM_STK_ANGLE_MU = 29.97767535
PARAM_STK_DIST_MU = 4.1876158
PARAM_STK_COV00 = 169.9862228
PARAM_STK_COV01 = 6.62318852
PARAM_STK_COV10 = 6.62318852
PARAM_STK_COV11 = 0.37123882


;;;;;;;;;;;;;;;;;;;;;;;; OTHERS
MISC_KERNEL_GAUSSIAN_SIGMAS = 4 ; how many sigmas of width should the precalculated gaussians have?
MISC_LOGAPBS_MIN = -2 ; log-apbs min cutoff
MISC_LOGAPBS_MAX =  3 ; log-apbs max cutoff


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; SMUTILS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
OG_STK_RADIUS = 2.0
OG_HBA_RADIUS = 2.0
OG_HBD_RADIUS = 2.0
OG_APBS_RADIUS = 2.0
OG_HPHOB_RADIUS = 2.0
OG_HPHIL_RADIUS = 2.0

DEBUG_CHEMTABLE_LIGAND = true


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
