; --------------------------------------------------------------------------;
;;;;;;;;;;;;;;;;;;;; READ BELOW BEFORE EDITING THIS FILE ;;;;;;;;;;;;;;;;;;;;
; --------------------------------------------------------------------------;

;;; This default configuration file is placed in VolGrids' repository root for convenience.
;;; As consequence, it is not packed when installing VolGrids as a package (e.g., via pip).
;;;
;;; Therefore, this file will only be used when NOT running VolGrids as a package
;;; (regardless of whether VolGrids is installed or not). For example:
;;;
;;; python3 volgrids smiffer -h                  --> uses this file
;;; python3 another/location/volgrids smiffer -h --> uses this file
;;; python3 -m volgrids smiffer -h               --> DOES NOT use this file
;;; volgrids smiffer -h                          --> DOES NOT use this file
;;;
;;; When this config file is not used, all parameters use default hardcoded values. They are the same as the ones in this file.
;;; In any case, this file can always be used by specifying its path with the -c/--config option.


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; VOLGRIDS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;; OUTPUT
REMOVE_OLD_CMAP_OUTPUT = true
GZIP_COMPRESSION = 9      ; gzip compression level for CMAP files (0-9); h5py default is 4
WARNING_GRID_SIZE = 5.0e7 ; if the grid would exceed this amount of points, trigger a warning with possibility to abort


;;;;;;;;;;;;;;;;;;;;;;;; BOX
USE_FIXED_DELTAS = true ; whether to use fixed dx,dy,dz and let xres,yres,zres change (or the opposite)
ENSURE_EQUILATERAL = false ; forces the grid to have the same resolution in all dimensions
EXTRA_BOX_SIZE = 5 ; extra padding at the box outlines, only applies to whole mode

;;; deltas used for calculations when USE_FIXED_DELTAS=true (resolutions change)
GRID_DX = 0.25
GRID_DY = 0.25
GRID_DZ = 0.25

;;; resolution used for calculations when USE_FIXED_DELTAS=false (deltas change)
GRID_XRES = 200
GRID_YRES = 200
GRID_ZRES = 200


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; SMIFFER ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;; OUTPUT
GRID_FORMAT_OUTPUT = CMAP_PACKED
    ; Format in which to pack the grid output. options:
    ; "DX": Human-readable format (heavy). Tested with VMD, Chimera, ChimeraX, UnityMol.
    ; "MRC": Binary format (light). Tested with VMD, Chimera, ChimeraX.
    ; "CCP4": Similar to MRC.
    ; "CMAP": Compressed binary format (very light). Tested with ChimeraX.
    ; "CMAP_PACKED": Instead of multiple files for every grid, pack all grids in a single file.

;;;;;;;;;;;;;;;;;;;;;;;; SMIFS
DO_SMIF_STACKING = true
DO_SMIF_HBA = true
DO_SMIF_HBD = true
DO_SMIF_HYDROPHOBIC = true
DO_SMIF_HYDROPHILIC = true
DO_SMIF_APBS = true

DO_SMIF_LOG_APBS = false
DO_SMIF_HYDRODIFF = false

USE_STRUCTURE_HYDROGENS = true ; whether to use the hydrogens from the structure (if available) for calculating hbdonors
HBONDS_ONLY_NUCLEOBASE = false


;;;;;;;;;;;;;;;;;;;;;;;; TRIMMING
;;; TOGGLES
DO_TRIMMING_OCCUPANCY = true
DO_TRIMMING_SPHERE    = true  ; only applies for pocket-sphere mode
DO_TRIMMING_RNDS      = false ; only applies for pocket-sphere mode. Can be problematic (e.g. slow, aggressive trimming); use with caution.
DO_TRIMMING_FARAWAY   = true  ; only applies for pocket-sphere mode
DO_TRIMMING_CAVITIES  = false ; run "cavities finder" and trim outside the cavities
TRIMMING_CAVITIES_THRESHOLD = 3.0 ; sensible values: 1,2,3. 0 (and below) deletes no points, 4 (and above) deletes all points
CAVITIES_NPASSES = 2 ; refine the cavities search by performing evenly spaced rotations between 0 and 90 degrees.
    ;;; CAVITIES_NPASSES = 1: one pass with the original grid orientation
    ;;; CAVITIES_NPASSES = 2: 0 deg rotation + 45 deg rotation , then average
    ;;; CAVITIES_NPASSES = 3: 0 deg + 30 deg + 60 deg rotations, then average
    ;;; and so on. Consider that a single rotation depends at most on 6 calls to scipy.ndimage.rotate
    ;;; it's recommended to set "ENSURE_EQUILATERAL=true" for better behaviour, specially near the grid boundaries (although it will increase computation time)

CAVITIES_WEIGHT = 0.0 ; values different than 0 will weight the SMIFs with the cavities values.

SAVE_TRIMMING_MASK = false ; saves the logical inverse of the trimming mask using TRIMMING_DIST_MID
SAVE_CAVITIES = false ; run "cavities finder" and save its grid

; NOTE: cavities options (DO_TRIMMING_CAVITIES, SAVE_CAVITIES) currently require DO_TRIMMING_OCCUPANCY to be true, otherwise they will be ignored

;;; OCCUPANCY TRIMMING
TRIMMING_DIST_SMALL = 2.5 ; used for: hydrophilic
TRIMMING_DIST_MID   = 3.0 ; used for: hydrophobic, hbonds, stacking
TRIMMING_DIST_LARGE = 3.5 ; used for: apbs

;;; RANDOM SEARCH TRIMMING
MAX_RNDS_DIST = inf
COG_CUBE_RADIUS = 4

;;; FARAWAY TRIMMING
TRIM_FARAWAY_DIST = 7.0 ; trim any point that is further than this distance from any atom in the structure


;;;;;;;;;;;;;;;;;;;;;;;; SMIF MODEL PARAMETERS
ENERGY_SCALE = 3.5 ; scale factor for the energy of the hbonds and stacking interactions

MU_HYDROPHOBIC = 4.4
SIGMA_HYDROPHOBIC = 0.3

MU_HYDROPHILIC = 3.0
SIGMA_HYDROPHILIC = 0.15

MU_ANGLE_HBA = 129.9
MU_DIST_HBA = 2.93
SIGMA_ANGLE_HBA = 20.0 ; 29.3 originally (given precisely)
SIGMA_DIST_HBA = 0.21

MU_ANGLE_HBD_FREE = 109.0
MU_DIST_HBD_FREE = 2.93
SIGMA_ANGLE_HBD_FREE = 20.0 ; 20.0 originally (inferred from .figure)
SIGMA_DIST_HBD_FREE = 0.21

MU_ANGLE_HBD_FIXED = 180.0
MU_DIST_HBD_FIXED = 2.93
SIGMA_ANGLE_HBD_FIXED = 30.0
SIGMA_DIST_HBD_FIXED = 0.21

MU_ANGLE_STACKING = 29.97767535
MU_DIST_STACKING = 4.1876158
COV_STACKING_00 = 169.9862228
COV_STACKING_01 = 6.62318852
COV_STACKING_10 = 6.62318852
COV_STACKING_11 = 0.37123882


;;;;;;;;;;;;;;;;;;;;;;;; OTHERS
GAUSSIAN_KERNEL_SIGMAS = 4 ; how many sigmas of width should the precalculated gaussians have?
APBS_MIN_CUTOFF = -2 ; log-apbs cutoff
APBS_MAX_CUTOFF = 3  ; log-apbs cutoff
